### ISSUE TITLE
towards paper: May 8 todos

### ISSUE THREAD

**Issue by ajvenkat** [GPCRviz/FlarePlot#2]
Flareplot charting area:
- [ ]  Swap the positions of the labels and tracks
- [ ]  Between the node-label and the corresponding track rectangle, synchronize the following action: on-click result (make track clickable), on-hover result
- [x]  Add play-button to the time slider

Website:
- [x]  Broken link on homepage of Flareplot: https://gpcrviz.github.io/FlarePlot/gpcr_demo.html
- [x]  Lowercase on the URL link of Flareplot: https://gpcrviz.github.io/FlarePlot/
- [x]  Optimize screen space on home page: refer to mockup (picture)
- [x]  Clicking a demo or example should bring you to a new clean page
- [x]  'Generate input' links on home page have different destinations
- [x]  New pages for uploaded files/examples
- [x]  Choose typeface for the website

For manuscript:
- [x]  GPCR interactome: cluster by protein family
- [ ]  Use B2AR deactivation simulation as an example for time series section

**Comment by RasmusFonseca** [comment]
Fingerprint page
- [x] Make td circular (`border-radius`)
- [ ] Highlight selected row (`tr`) both the active one and the hovered one. 
- [x] Keep the headers from scrolling

Clickable tissues
- [ ] Some kind of legend explaining the colors

**Comment by RasmusFonseca** [comment]
@RasmusFonseca
- [x] Separator between "Time" and "Compare".  
- [ ] Frame 0 of mor... datafile doesn't match flareplot
- [x] Upload needs to work ASAP. 
- [ ] Make sure the upload page has dropdowns for tree and track selection.
- [x] Get gpcr-side-by-side in time demo wheel
- [ ] Smaller flareplot on demos

@akma327 
- [x] Finish up scrolling fingerprints (Anthony)
- [ ] Single-bar next/prev cycling
- [x] Document how to embed fingerprints

Anyone
- [ ] Make the tracks on the temporal half-height.

**Comment by RasmusFonseca** [comment]
- [x] Info on front page
- [x] At least 3 examples for temporal
- [x] First example should be smaller (load faster)
- [x] For the side-by-side remove loops
- [ ] Bold menu item for the currently active site. 
- [x] Clicking the track (!)
- [x] Transfer the old [Evobundle content](http://rasmusfonseca.github.io/EvoBundle/) to the upload page
- [ ] No action happens when the 'About' link is clicked. Resuse the content from this page on the About page: https://github.com/GPCRviz/flareplot
- [x] In the 'Create' page, under the "generate your own json..." the link for the Json scripts appears to be broken: https://gpcrviz.github.io/flareplot/?p=create
